### PR TITLE
More speeds and ability to force higher speeds

### PR DESCRIPTION
**Pull request by odie5533**
I added more speeds to the radio buttons (you might want to leave them off or reduce them) and the ability to force higher speeds. The forcing higher speeds is very useful if the user decides to add more speeds themselves since anything above 2 won't work without the fix.

### CODE REVIEW

**Comment by odie5533** [comment]
Also, thank you very much for making this script! I've been getting more and more annoyed having to set the speed every time I watch a video, and this not only makes it remember the speed I set but makes it easier to change the speed as well. Thanks!

**Comment by splttingatms** [comment]
Thanks for the contribution @odie5533! I didn't even know you could force the speed to values higher than what is shown in the player menu. I found the YouTube Player API exposes a [getAvailablePlaybackRates](https://developers.google.com/youtube/iframe_api_reference#getAvailablePlaybackRates) function that may be of some future use.

As far as the edit, can you merge `forcePlaybackRate` into `setPlaybackRate`, that way there is only one function to set the rate. 

Also I see that `forcePlaybackRate` calls a `setPlaybackRate(r)` function, which doesn't exist. It would be best to refactor the current `setPlaybackRate` to take in the rate as a parameter, and have a new function called `setPlaybackRateToPreference` that retrieves the saved preferred speed from GM and pass it to `setPlaybackRate(r)` function. Something like this:

``` javascript
function setPlaybackRateToPreference() {
   var rate = GM_getValue("playbackRate", 1);
   setPlaybackRate(rate);
}

function setPlaybackRate(rate) {
   ... set rate on movie_player and video-stream objects
}
```

**Comment by splttingatms** [comment]
So I tested the two methods of setting playback rate. Great find on the video-stream object! Setting the playback rate through that object actually allows you to set the playback rate up to 10x! I was testing on this [metronome video](https://www.youtube.com/watch?v=gsJEMH_emBM).

There are two objects that allow you to set the playback rate:
- movie_player: Defines a `setPlaybackRate` function. Values beyond the defined list in player menu will be ignored. Setting the value here will update the player menu accordingly. 
  `$("#movie_player").setPlaybackRate(1)`
- video-stream: Defines a playbackRate property that can be set directly. Can set the value larger than what is shown in the player menu. Setting the value here **will not** update the player menu.
  `$(".video-stream").playbackRate = 10`

Player Menu
image

Notes:
- Video-stream seems to cap out at 10.
- Video-stream can break movie_player. movie_player.setPlaybackRate(r) will stop updating the video speed (but still update the playback menu) if you set video-stream.playbackRate to large values (10). In other words, movie_player does not guarantee speed will update. This indicates that we should keep both values in sync so that the speed is updated via video-stream and the menu updates via movie_player. Example of when speed is not updated:

``` javascript
$(".video-stream").playbackRate = 10;
$("#movie_player").setPlaybackRate(1); // updates player menu but not speed
```

**Comment by odie5533** [comment]
I refactored the function as you recommended, and I fixed the bug with the setPlaybackRate() function (it was meant to be a recursive call).

**Pull request merged**
